# Generated by Django 4.1.4 on 2022-12-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, default='postimages/default.png', null=True, upload_to='postimages/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
